export const resizableBoxStyles = {
  rootCls: {
    base: "outline-none inline-flex items-center justify-center whitespace-nowrap transition-all duration-150 ease-in-out !leading-none",
    colors: {
      blue: "text-white bg-blue-500 ",
      red: "text-white bg-red-500 ",
      orange: "text-white bg-orange-500 ",
      yellow: "text-white bg-yellow-500 ",
      purple: "text-white bg-purple-500 ",
      green: "text-white bg-green-500 ",
      default: "text-white bg-default-500 ",
    },
  },
  handleCls: {
    top: {
      base: "!h-px flex justify-center after:content-[''] after:absolute after:top-[-5px] after:block after:w-12 after:h-1.5  after:rounded-full",
      colors: {
        blue: "bg-blue-500 after:bg-blue-500",
        red: "bg-red-500 after:bg-red-500",
        orange: "bg-orange-500 after:bg-orange-500",
        yellow: "bg-yellow-500 after:bg-yellow-500",
        purple: "bg-purple-500 after:bg-purple-500",
        green: "bg-green-500 after:bg-green-500",
        default: "bg-default-600 after:bg-default-600",
      },
    },
    right: {
      base: "!w-px flex items-center after:content-[''] after:absolute after:block after:w-1.5 after:h-12 after:rounded-full",
      colors: {
        blue: "bg-blue-500 after:bg-blue-500",
        red: "bg-red-500 after:bg-red-500",
        orange: "bg-orange-500 after:bg-orange-500",
        yellow: "bg-yellow-500 after:bg-yellow-500",
        purple: "bg-purple-500 after:bg-purple-500",
        green: "bg-green-500 after:bg-green-500",
        default: "bg-default-600 after:bg-default-600",
      },
    },
    bottom: {
      base: "!h-px flex justify-center after:content-[''] after:absolute after:block after:w-12 after:h-1.5  after:rounded-full",
      colors: {
        blue: "bg-blue-500 after:bg-blue-500",
        red: "bg-red-500 after:bg-red-500",
        orange: "bg-orange-500 after:bg-orange-500",
        yellow: "bg-yellow-500 after:bg-yellow-500",
        purple: "bg-purple-500 after:bg-purple-500",
        green: "bg-green-500 after:bg-green-500",
        default: "bg-default-600 after:bg-default-600",
      },
    },
    left: {
      base: "!w-px flex items-center before:content-[''] before:absolute before:left-[-5px] before:block before:w-1.5 before:h-12 before:rounded-full",
      colors: {
        blue: "bg-blue-500 before:bg-blue-500",
        red: "bg-red-500 before:bg-red-500",
        orange: "bg-orange-500 before:bg-orange-500",
        yellow: "bg-yellow-500 before:bg-yellow-500",
        purple: "bg-purple-500 before:bg-purple-500",
        green: "bg-green-500 before:bg-green-500",
        default: "bg-default-600 before:bg-default-600",
      },
    },
    topRight: {
      base: "flex items-start justify-end after:content-[''] after:block after:rounded-full after:w-3 after:h-3",
      colors: {
        blue: "after:bg-blue-500",
        red: "after:bg-red-500",
        orange: "after:bg-orange-500",
        yellow: "after:bg-yellow-500",
        purple: "after:bg-purple-500",
        green: "after:bg-green-500",
        default: "after:bg-default-600",
      },
    },
    bottomRight: {
      base: "flex items-end justify-end after:content-[''] after:block after:rounded-full after:w-3 after:h-3",
      colors: {
        blue: "after:bg-blue-500",
        red: "after:bg-red-500",
        orange: "after:bg-orange-500",
        yellow: "after:bg-yellow-500",
        purple: "after:bg-purple-500",
        green: "after:bg-green-500",
        default: "after:bg-default-600",
      },
    },
    bottomLeft: {
      base: "flex items-end justify-start after:content-[''] after:block after:rounded-full after:w-3 after:h-3",
      colors: {
        blue: "after:bg-blue-500",
        red: "after:bg-red-500",
        orange: "after:bg-orange-500",
        yellow: "after:bg-yellow-500",
        purple: "after:bg-purple-500",
        green: "after:bg-green-500",
        default: "after:bg-default-600",
      },
    },
    topLeft: {
      base: "flex items-start justify-start after:content-[''] after:block after:rounded-full after:w-3 after:h-3",
      colors: {
        blue: "after:bg-blue-500",
        red: "after:bg-red-500",
        orange: "after:bg-orange-500",
        yellow: "after:bg-yellow-500",
        purple: "after:bg-purple-500",
        green: "after:bg-green-500",
        default: "after:bg-default-600",
      },
    },
  },
  colors: {
    blue: "bg-blue-500 after:bg-blue-500",
    red: "bg-red-500 after:bg-red-500",
    orange: "bg-orange-500 after:bg-orange-500",
    yellow: "bg-yellow-500 after:bg-yellow-500",
    purple: "bg-purple-500 after:bg-purple-500",
    green: "bg-green-500 after:bg-green-500",
    default: "bg-default-500 after:bg-default-500",
  },
};
