export const calculatorStyles = {
  baseCls: 'grid',
  containerCls: 'border border-b border-secondary-150 rounded-md p-2',
  displayCls:
    'w-full flex flex-wrap gap-0.5 justify-end items-center outline-none border border-secondary-light rounded-md p-2 mb-3',
  // spanCls: {
  //   1: 'col-span-1',
  //   2: 'col-span-2',
  //   3: 'col-span-3',
  //   4: 'col-span-4',
  //   5: 'col-span-5',
  //   6: 'col-span-6',
  //   7: 'col-span-7',
  //   8: 'col-span-8',
  //   9: 'col-span-9',
  //   10: 'col-span-10',
  //   11: 'col-span-11',
  //   12: 'col-span-12'
  // },
  buttonCls: {
    base: 'uppercase !text-secondary hover:!text-secondary-dark border !border-black !border-opacity-10',
    colspan: {
      1: 'col-span-1',
      2: 'col-span-2',
      3: 'col-span-3',
      4: 'col-span-4',
      5: 'col-span-5',
      6: 'col-span-6',
      7: 'col-span-7',
      8: 'col-span-8',
      9: 'col-span-9',
      10: 'col-span-10',
      11: 'col-span-11',
      12: 'col-span-12'
    },
    color: {
      inherit: '!bg-inherit',
      'primary-50': '!bg-primary-50 hover:!bg-primary-100',
      'primary-100': '!bg-primary-100 hover:!bg-primary-light',
      'primary-light': '!bg-primary-light',
      primary: '!bg-primary',
      'primary-dark': '!bg-primary-dark',
      'primary-darker': '!bg-primary-darker',
      'secondary-50': '!bg-secondary-50 hover:!bg-secondary-100',
      'secondary-100': '!bg-secondary-100 hover:!bg-secondary-light',
      'secondary-light': '!bg-secondary-light',
      secondary: '!bg-secondary',
      'secondary-dark': '!bg-secondary-dark',
      'secondary-darker': '!bg-secondary-darker',
      'info-50': '!bg-info-50 hover:!bg-info-100',
      'info-100': '!bg-info-100 hover:!bg-info-light',
      'info-light': '!bg-info-light',
      info: '!bg-info',
      'info-dark': '!bg-info-dark',
      'info-darker': '!bg-info-darker',
      'success-50': '!bg-success-50 hover:!bg-success-100',
      'success-100': '!bg-success-100 hover:!bg-success-light',
      'success-light': '!bg-success-light',
      success: '!bg-success',
      'success-dark': '!bg-success-dark',
      'success-darker': '!bg-success-darker',
      'warning-50': '!bg-warning-50 hover:!bg-warning-100',
      'warning-100': '!bg-warning-100 hover:!bg-warning-light',
      'warning-light': '!bg-warning-light',
      warning: '!bg-warning hover:!bg-warning-dark',
      'warning-dark': '!bg-warning-dark',
      'warning-darker': '!bg-warning-darker',
      'danger-50': '!bg-danger-50 hover:!bg-danger-100',
      'danger-100': '!bg-danger-100 hover:!bg-danger-light',
      'danger-light': '!bg-danger-light',
      danger: '!bg-danger',
      'danger-dark': '!bg-danger-dark',
      'danger-darker': '!bg-danger-darker',
      'default-50': '!bg-secondary-50 hover:!bg-secondary-100',
      'default-100': '!bg-secondary-100 hover:!bg-secondary-light',
      'default-light': '!bg-secondary-light',
      default: '!bg-default',
      'default-dark': '!bg-secondary-dark',
      'default-darker': '!bg-secondary-darker'
    }
  }
}
