export const iconStyles = {
  baseCls: 'inline-flex items-center justify-center !leading-none',
  sizeCls: {
    sm: 'text-sm',
    default: 'text-base',
    md: 'text-md',
    lg: 'text-lg'
  },
  colorCls: {
    inherit: 'text-inherit',
    'primary-50': 'text-primary-50',
    'primary-100': 'text-primary-100',
    'primary-light': 'text-primary-light',
    primary: 'text-primary',
    'primary-dark': 'text-primary-dark',
    'primary-darker': 'text-primary-darker',
    'secondary-50': 'text-secondary-50',
    'secondary-100': 'text-secondary-100',
    'secondary-light': 'text-secondary-light',
    secondary: 'text-secondary',
    'secondary-dark': 'text-secondary-dark',
    'secondary-darker': 'text-secondary-darker',
    'info-50': 'text-info-50',
    'info-100': 'text-info-100',
    'info-light': 'text-info-light',
    info: 'text-info',
    'info-dark': 'text-info-dark',
    'info-darker': 'text-info-darker',
    'success-50': 'text-success-50',
    'success-100': 'text-success-100',
    'success-light': 'text-success-light',
    success: 'text-success',
    'success-dark': 'text-success-dark',
    'success-darker': 'text-success-darker',
    'warning-50': 'text-warning-50',
    'warning-100': 'text-warning-100',
    'warning-light': 'text-warning-light',
    warning: 'text-warning',
    'warning-dark': 'text-warning-dark',
    'warning-darker': 'text-warning-darker',
    'danger-50': 'text-danger-50',
    'danger-100': 'text-danger-100',
    'danger-light': 'text-danger-light',
    danger: 'text-danger',
    'danger-dark': 'text-danger-dark',
    'danger-darker': 'text-danger-darker',
    'default-50': 'text-secondary-50',
    'default-100': 'text-secondary-100',
    'default-light': 'text-secondary-light',
    default: 'text-default',
    'default-dark': 'text-secondary-dark',
    'default-darker': 'text-secondary-darker',
    white: 'text-white'
  }
}
